name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813  # v1.4.3
      with:
        # Using audit because some endpoints are not reliably fixed. We could
        # try to nail them down, but it would turn into a game of whack-a-mole.
        egress-policy: audit
        disable-telemetry: true
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
    - name: set up JDK 8
      uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142  # v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn package --file pom.xml -DskipTests
    - name: Test
      run: mvn test --file pom.xml -X
