name: Build and run tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Deny all default permissions globally
permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
      with:
        # Using audit because some endpoints are not reliably fixed. We could
        # try to nail them down, but it would turn into a game of whack-a-mole.
        egress-policy: audit
        disable-telemetry: true
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: set up JDK 21
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn package --file pom.xml -DskipTests
    - name: Test
      run: mvn test --file pom.xml -X
